### ISSUE TITLE
DelaTable function returns old structure when new columns have been merged

### ISSUE THREAD

**Issue by nitzmali** [jeppe742/DeltaLakeReader#15]
from deltalake import DeltaTable
df = DeltaTable("path_to_delta_table",file_system=fs).to_pandas()

I am using latest version of delta lake reader. I am reading a delta table using the above function. Recently I had updated my delta table by using merge schema and adding new columns to the delta table. Now, when I read the table after the merge I don't see new columns in the results. I tested this by reading through Spark Context and I see new columns. 

spark.read.format("delta").load()  

Any Help?

Thank You 
Nitin

**Comment by jeppe742** [comment]
Hey Nitin,

very interesting issue. I guess the issue is that when you merge the schema, some files will have more columns than others.
And when you ask PyArrow to read the parquet files, it will only take the columns that exists in all files.

Think you can pass a schema to PyArrow, so I might take a look in the weekend if that can be used to fix the issue.
Otherwise it might be a tricky issue, since I have just "out-sourced" the I/O to PyArrow

**Comment by nitzmali** [comment]
Hi @jeppe742 
Yes, Your'e right. You should be able to pass the schema to PyArrow. Let's Hope If this works out. Else, we can try some other alternatives.

**Comment by jeppe742** [comment]
@nitzmali Think I found a solution.
Now It should try to take the schema of the latest file (for a given version) and pass that as the schema to PyArrow. Updated package to 0.2.5, let me know if you run into any other issues :smiley:
